name: CAA
channels:
  - anaconda
  - pchrapka
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1h=haf1e3a3_0
  - pip=20.2.4=py38_0
  - python=3.8.5=h26836e1_1
  - readline=8.0=h1de35cc_0
  - setuptools=50.3.0=py38h0dc7051_1
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - cachetools==4.2.0
    - chardet==4.0.0
    - cycler==0.10.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - joblib==1.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.3
    - numpy==1.19.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - pillow==8.0.1
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.24.0
    - scipy==1.4.1
    - seaborn==0.9.0
    - six==1.15.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /Users/weikaiqi/anaconda3/envs/CAA

